#!/usr/bin/env bash

set -e

. $(dirname $0)/post-process-helpers

# Parse our options
while getopts "n:o:" OPT; do
        case "${OPT}" in
        o)  output="${OPTARG}";;
        n)  base_name="${OPTARG}";;
        :)  error "option '%s' expects a mandatory argument\n" "${OPTARG}";;
        \?) error "unknown option '%s'\n" "${OPTARG}";;
        esac
done

# Already vendored tarball, nothing to do
if tar tf ${output} | grep -q "^[^/]*/vendor" ; then
	exit 0
fi

unpack ${base_name} ${output}

# Do the Go vendoring
pushd ${base_name} > /dev/null
go mod vendor -v
popd > /dev/null

repack ${base_name} ${output}
